# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kATdG-CnZhtrEJyT2j9GTVhkUQACXF9R
"""

import streamlit as st
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# ===============================
# PAGE CONFIG
# ===============================
st.set_page_config(
    page_title="Financial Freedom Consultant",
    layout="wide"
)

# ===============================
# GLOBAL STYLE (DARK PROFESSIONAL DASHBOARD)
# ===============================
st.markdown("""
<style>
html, body, [class*="css"] {
    font-family: 'Segoe UI', sans-serif;
    background-color: #0b0f19;
    color: #e5e7eb;
}

[data-testid="stSidebar"] {
    background-color: #111827;
}

.dashboard-card {
    background-color: #111827;
    border: 1px solid #1f2937;
    border-radius: 14px;
    padding: 18px;
    text-align: center;
}

.card-title {
    font-size: 13px;
    color: #9ca3af;
}

.card-value {
    font-size: 22px;
    font-weight: 600;
    color: #f9fafb;
}

.section-title {
    font-size: 18px;
    font-weight: 600;
    margin-bottom: 10px;
}

hr {
    border: none;
    border-top: 1px solid #1f2937;
    margin: 25px 0;
}
</style>
""", unsafe_allow_html=True)

plt.style.use("dark_background")

# ===============================
# HEADER
# ===============================
st.markdown("## 💼 Financial Freedom Consultant")
st.caption("Professional financial planning dashboard for long term wealth and passive income")

st.markdown("<hr>", unsafe_allow_html=True)

# ===============================
# SIDEBAR INPUT
# ===============================
st.sidebar.markdown("## 📌 User Profile")

usia_sekarang = st.sidebar.number_input(
    "Usia saat ini",
    min_value=18,
    max_value=80,
    value=None,
    placeholder="Contoh: 25"
)

usia_target = st.sidebar.number_input(
    "Target usia financial freedom",
    min_value=18,
    max_value=100,
    value=None,
    placeholder="Contoh: 50"
)

target_aset = st.sidebar.number_input(
    "Target aset saat financial freedom (Rp)",
    min_value=0,
    value=None,
    step=100_000_000,
    placeholder="Contoh: 3000000000"
)

profil_investor = st.sidebar.selectbox(
    "Profil investor",
    ["", "Konservatif", "Moderat", "Agresif"]
)

expert_mode = st.sidebar.checkbox("Aktifkan Expert Mode")

# ===============================
# VALIDATION
# ===============================
if not all([usia_sekarang, usia_target, target_aset, profil_investor]):
    st.info("Lengkapi seluruh input di sidebar untuk menampilkan dashboard.")
    st.stop()

if usia_target <= usia_sekarang:
    st.error("Target usia harus lebih besar dari usia saat ini.")
    st.stop()

# ===============================
# ASSUMPTIONS
# ===============================
return_map = {
    "Konservatif": 0.07,
    "Moderat": 0.11,
    "Agresif": 0.16
}

expected_return = return_map[profil_investor]
horizon = usia_target - usia_sekarang
months = horizon * 12
monthly_rate = expected_return / 12

# ===============================
# CORE CALCULATION
# ===============================
monthly_investment = target_aset * monthly_rate / ((1 + monthly_rate) ** months - 1)

balance = 0
balances = []
invested = []
ages = []
total_invested = 0

for year in range(1, horizon + 1):
    for _ in range(12):
        balance = balance * (1 + monthly_rate) + monthly_investment
        total_invested += monthly_investment
    balances.append(balance)
    invested.append(total_invested)
    ages.append(usia_sekarang + year)

df = pd.DataFrame({
    "Usia": ages,
    "Total Aset": balances,
    "Dana Disetor": invested
})

# ===============================
# KPI DASHBOARD CARDS
# ===============================
st.markdown("### 📊 Ringkasan Finansial")

c1, c2, c3, c4 = st.columns(4)

with c1:
    st.markdown(f"""
    <div class="dashboard-card">
        <div class="card-title">Target Usia</div>
        <div class="card-value">{usia_target} tahun</div>
    </div>
    """, unsafe_allow_html=True)

with c2:
    st.markdown(f"""
    <div class="dashboard-card">
        <div class="card-title">Profil Investor</div>
        <div class="card-value">{profil_investor}</div>
    </div>
    """, unsafe_allow_html=True)

with c3:
    st.markdown(f"""
    <div class="dashboard-card">
        <div class="card-title">Return Tahunan</div>
        <div class="card-value">{expected_return*100:.1f}%</div>
    </div>
    """, unsafe_allow_html=True)

with c4:
    st.markdown(f"""
    <div class="dashboard-card">
        <div class="card-title">Investasi Bulanan</div>
        <div class="card-value">Rp {monthly_investment:,.0f}</div>
    </div>
    """, unsafe_allow_html=True)

st.markdown("<hr>", unsafe_allow_html=True)

# ===============================
# VISUALIZATION SECTION
# ===============================
st.markdown("### 📈 Proyeksi & Analisis")

g1, g2 = st.columns(2)

# --- GRAPH 1: Asset Growth
fig1, ax1 = plt.subplots(figsize=(6,4))
ax1.plot(df["Usia"], df["Total Aset"], linewidth=2)
ax1.axhline(target_aset, linestyle="--", linewidth=1)
ax1.set_title("Pertumbuhan Aset")
ax1.set_xlabel("Usia")
ax1.set_ylabel("Nilai Aset (Rp)")
ax1.ticklabel_format(style="plain", axis="y")

final_asset = df["Total Aset"].iloc[-1]
ax1.text(
    df["Usia"].iloc[-1],
    final_asset,
    f" Rp {final_asset:,.0f}",
    ha="right",
    va="bottom"
)

g1.pyplot(fig1)

# --- GRAPH 2: Invested vs Growth
fig2, ax2 = plt.subplots(figsize=(6,4))
ax2.plot(df["Usia"], df["Dana Disetor"], label="Dana Disetor", linewidth=2)
ax2.plot(df["Usia"], df["Total Aset"], label="Total Aset", linewidth=2)
ax2.set_title("Dana Disetor vs Hasil Investasi")
ax2.legend()
ax2.ticklabel_format(style="plain", axis="y")

ax2.text(
    df["Usia"].iloc[-1],
    df["Dana Disetor"].iloc[-1],
    f" Rp {df['Dana Disetor'].iloc[-1]:,.0f}",
    ha="right",
    va="bottom"
)

g2.pyplot(fig2)

st.markdown("<hr>", unsafe_allow_html=True)

# ===============================
# SCENARIO ANALYSIS TABLE
# ===============================
st.markdown("### 📋 Scenario Analysis")

scenario_data = []

for label, r in {
    "Pesimis": expected_return - 0.03,
    "Base Case": expected_return,
    "Optimis": expected_return + 0.03
}.items():
    rate = r / 12
    bal = 0
    for _ in range(months):
        bal = bal * (1 + rate) + monthly_investment
    scenario_data.append([label, f"{r*100:.1f}%", f"Rp {bal:,.0f}"])

df_scenario = pd.DataFrame(
    scenario_data,
    columns=["Skenario", "Return Tahunan", "Estimasi Aset Akhir"]
)

st.dataframe(df_scenario, use_container_width=True)

# ===============================
# PASSIVE INCOME SIMULATOR
# ===============================
st.markdown("<hr>", unsafe_allow_html=True)
st.markdown("### 💸 Simulasi Pendapatan Pasif")

yield_obligasi = st.slider(
    "Yield obligasi tahunan (%)",
    min_value=3.0,
    max_value=12.0,
    value=6.0
) / 100

annual_income = target_aset * yield_obligasi
monthly_income = annual_income / 12

p1, p2, p3 = st.columns(3)

with p1:
    st.markdown(f"""
    <div class="dashboard-card">
        <div class="card-title">Total Aset</div>
        <div class="card-value">Rp {target_aset:,.0f}</div>
    </div>
    """, unsafe_allow_html=True)

with p2:
    st.markdown(f"""
    <div class="dashboard-card">
        <div class="card-title">Pendapatan Tahunan</div>
        <div class="card-value">Rp {annual_income:,.0f}</div>
    </div>
    """, unsafe_allow_html=True)

with p3:
    st.markdown(f"""
    <div class="dashboard-card">
        <div class="card-title">Pendapatan Bulanan</div>
        <div class="card-value">Rp {monthly_income:,.0f}</div>
    </div>
    """, unsafe_allow_html=True)

st.info(
    "Simulasi ini mengasumsikan seluruh aset dialokasikan ke obligasi dan "
    "kupon digunakan sebagai pendapatan tanpa mengurangi pokok investasi."
)

# ===============================
# DISCLAIMER
# ===============================
st.caption(
    "Disclaimer: Aplikasi ini bersifat edukatif dan bukan merupakan nasihat investasi."
)
