# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kATdG-CnZhtrEJyT2j9GTVhkUQACXF9R
"""

import streamlit as st
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# ===============================
# PAGE CONFIG
# ===============================
st.set_page_config(
    page_title="Financial Freedom Consultant",
    layout="wide"
)

# ===============================
# GLOBAL STYLE (DARK PROFESSIONAL DASHBOARD)
# ===============================
st.markdown("""
<style>
html, body, [class*="css"] {
    font-family: 'Segoe UI', sans-serif;
    background-color: #0b0f19;
    color: #e5e7eb;
}

[data-testid="stSidebar"] {
    background-color: #111827;
}

.dashboard-card {
    background-color: #111827;
    border: 1px solid #1f2937;
    border-radius: 14px;
    padding: 18px;
    text-align: center;
}

.card-title {
    font-size: 13px;
    color: #9ca3af;
}

.card-value {
    font-size: 22px;
    font-weight: 600;
    color: #f9fafb;
}

.section-title {
    font-size: 18px;
    font-weight: 600;
    margin-bottom: 10px;
}

hr {
    border: none;
    border-top: 1px solid #1f2937;
    margin: 25px 0;
}
</style>
""", unsafe_allow_html=True)

plt.style.use("dark_background")

# ===============================
# HEADER
# ===============================
st.markdown("## 💼 Financial Freedom Consultant")
st.caption("Professional financial planning dashboard for long term wealth and passive income")

st.markdown("<hr>", unsafe_allow_html=True)

# ===============================
# SIDEBAR INPUT
# ===============================
st.sidebar.markdown("## 📌 User Profile")

usia_sekarang = st.sidebar.number_input(
    "Usia saat ini",
    min_value=18,
    max_value=80,
    value=None,
    placeholder="Contoh: 25"
)

usia_target = st.sidebar.number_input(
    "Target usia financial freedom",
    min_value=18,
    max_value=100,
    value=None,
    placeholder="Contoh: 50"
)

target_aset = st.sidebar.number_input(
    "Target aset saat financial freedom (Rp)",
    min_value=0,
    value=None,
    step=100_000_000,
    placeholder="Contoh: 3000000000"
)

profil_investor = st.sidebar.selectbox(
    "Profil investor",
    ["", "Konservatif", "Moderat", "Agresif"]
)

expert_mode = st.sidebar.checkbox("Aktifkan Expert Mode")

# ===============================
# VALIDATION
# ===============================
if not all([usia_sekarang, usia_target, target_aset, profil_investor]):
    st.info("Lengkapi seluruh input di sidebar untuk menampilkan dashboard.")
    st.stop()

if usia_target <= usia_sekarang:
    st.error("Target usia harus lebih besar dari usia saat ini.")
    st.stop()

# ===============================
# ASSUMPTIONS
# ===============================
return_map = {
    "Konservatif": 0.07,
    "Moderat": 0.11,
    "Agresif": 0.16
}

expected_return = return_map[profil_investor]
horizon = usia_target - usia_sekarang
months = horizon * 12
monthly_rate = expected_return / 12

import streamlit as st
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet
import io

# ===============================
# PAGE CONFIG
# ===============================
st.set_page_config(page_title="Financial Freedom Consultant", layout="wide")

# ===============================
# MODE TOGGLE
# ===============================
dark_mode = st.toggle("🌙 Dark Mode", value=True)

if dark_mode:
    bg, card, border, text = "#0b0f19", "#111827", "#1f2937", "#e5e7eb"
    plt.style.use("dark_background")
else:
    bg, card, border, text = "#f9fafb", "#ffffff", "#e5e7eb", "#111827"
    plt.style.use("default")

# ===============================
# GLOBAL CSS
# ===============================
st.markdown(f"""
<style>
html, body {{ background-color:{bg}; color:{text}; }}
[data-testid="stSidebar"] {{ background-color:{card}; }}
.dashboard-card {{
    background:{card}; border:1px solid {border};
    border-radius:14px; padding:18px; text-align:center;
}}
.card-title {{ font-size:13px; color:#9ca3af; }}
.card-value {{ font-size:22px; font-weight:600; }}
</style>
""", unsafe_allow_html=True)

# ===============================
# HEADER
# ===============================
st.markdown("## 💼 Financial Freedom Consultant Dashboard")
st.caption("Advanced interactive financial planning dashboard")

# ===============================
# SIDEBAR INPUT
# ===============================
st.sidebar.header("📌 Profil Pengguna")

usia_sekarang = st.sidebar.number_input("Usia saat ini", 18, 80, value=None)
usia_target = st.sidebar.number_input("Target usia financial freedom", 18, 100, value=None)
target_aset = st.sidebar.number_input("Target aset (Rp)", value=None, step=100_000_000)
profil = st.sidebar.selectbox("Profil investor", ["", "Konservatif", "Moderat", "Agresif"])
import streamlit as st
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import io

from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet

# =====================================================
# PAGE CONFIG
# =====================================================
st.set_page_config(
    page_title="Financial Freedom Consultant",
    layout="wide",
    initial_sidebar_state="expanded"
)

# =====================================================
# STATE INIT
# =====================================================
if "dark_mode" not in st.session_state:
    st.session_state.dark_mode = True

# =====================================================
# MODE TOGGLE
# =====================================================
st.session_state.dark_mode = st.toggle(
    "🌙 Dark Mode",
    value=st.session_state.dark_mode,
    key="dark_mode_toggle"
)

if st.session_state.dark_mode:
    bg = "#0b0f19"
    card = "#111827"
    border = "#1f2937"
    text = "#e5e7eb"
    muted = "#9ca3af"
    plt.style.use("dark_background")
else:
    bg = "#f9fafb"
    card = "#ffffff"
    border = "#e5e7eb"
    text = "#111827"
    muted = "#6b7280"
    plt.style.use("default")

# =====================================================
# GLOBAL CSS (TYPOGRAPHY + LAYOUT)
# =====================================================
st.markdown(f"""
<style>
html, body, [class*="css"] {{
    background-color: {bg};
    color: {text};
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI",
                 Roboto, "Inter", Helvetica, Arial, sans-serif;
    letter-spacing: -0.2px;
}}

h1, h2, h3 {{
    font-weight: 600;
    letter-spacing: -0.6px;
}}

.dashboard-card {{
    background: {card};
    border: 1px solid {border};
    border-radius: 14px;
    padding: 18px;
    min-height: 90px;
}}

.card-title {{
    font-size: 0.72rem;
    text-transform: uppercase;
    letter-spacing: 0.08em;
    color: {muted};
    margin-bottom: 6px;
}}

.card-value {{
    font-size: 1.5rem;
    font-weight: 600;
}}

[data-testid="stMetricValue"] {{
    font-size: 1.6rem;
    font-weight: 600;
}}

[data-testid="stMetricLabel"] {{
    font-size: 0.75rem;
    text-transform: uppercase;
    letter-spacing: 0.08em;
    color: {muted};
}}

thead tr th {{
    font-size: 0.75rem;
    text-transform: uppercase;
    letter-spacing: 0.08em;
}}

tbody tr td {{
    font-size: 0.85rem;
}}
</style>
""", unsafe_allow_html=True)

# =====================================================
# HEADER
# =====================================================
st.markdown("## 💼 Financial Freedom Consultant Dashboard")
st.caption("Interactive personal financial planning dashboard")

# =====================================================
# SIDEBAR INPUT
# =====================================================
st.sidebar.header("📌 Profil Finansial")

usia_sekarang = st.sidebar.number_input(
    "Usia saat ini",
    min_value=18,
    max_value=80,
    value=None,
    key="usia_sekarang"
)

usia_target = st.sidebar.number_input(
    "Target usia financial freedom",
    min_value=18,
    max_value=100,
    value=None,
    key="usia_target"
)

target_aset = st.sidebar.number_input(
    "Target aset (Rp)",
    value=None,
    step=100_000_000,
    key="target_aset"
)

profil = st.sidebar.selectbox(
    "Profil investor",
    ["", "Konservatif", "Moderat", "Agresif"],
    key="profil_investor"
)

if not all([usia_sekarang, usia_target, target_aset, profil]):
    st.info("Lengkapi seluruh input di sidebar untuk memulai analisis.")
    st.stop()

# =====================================================
# RETURN SLIDER
# =====================================================
return_range = {
    "Konservatif": (0.05, 0.09),
    "Moderat": (0.08, 0.14),
    "Agresif": (0.13, 0.19)
}

r_min, r_max = return_range[profil]

expected_return = st.slider(
    "🎛 Asumsi return tahunan",
    min_value=r_min,
    max_value=r_max,
    value=(r_min + r_max) / 2,
    step=0.001,
    format="%.2f",
    key="return_slider"
)

# =====================================================
# CORE CALCULATION
# =====================================================
years = usia_target - usia_sekarang
months = years * 12
monthly_rate = expected_return / 12

monthly_invest = (
    target_aset * monthly_rate /
    ((1 + monthly_rate) ** months - 1)
)

balance = 0
balances = []
invested = []
ages = []
total_invested = 0

for year in range(1, years + 1):
    for _ in range(12):
        balance = balance * (1 + monthly_rate) + monthly_invest
        total_invested += monthly_invest
    balances.append(balance)
    invested.append(total_invested)
    ages.append(usia_sekarang + year)

df = pd.DataFrame({
    "Usia": ages,
    "Aset": balances,
    "Dana Disetor": invested
})

# =====================================================
# KPI CARDS
# =====================================================
c1, c2, c3, c4 = st.columns(4)

def card(col, title, value):
    col.markdown(f"""
    <div class="dashboard-card">
        <div class="card-title">{title}</div>
        <div class="card-value">{value}</div>
    </div>
    """, unsafe_allow_html=True)

card(c1, "Target Usia", f"{usia_target} Tahun")
card(c2, "Profil Investor", profil)
card(c3, "Return Tahunan", f"{expected_return*100:.2f}%")
card(c4, "Investasi Bulanan", f"Rp {monthly_invest:,.0f}")

# =====================================================
# MAIN CHARTS
# =====================================================
g1, g2 = st.columns(2)

fig1, ax1 = plt.subplots()
ax1.plot(df["Usia"], df["Aset"], linewidth=3)
ax1.scatter(df["Usia"].iloc[-1], df["Aset"].iloc[-1])
ax1.set_title("Pertumbuhan Aset")
ax1.text(df["Usia"].iloc[-1], df["Aset"].iloc[-1],
         f" Rp {df['Aset'].iloc[-1]:,.0f}")
g1.pyplot(fig1)

fig2, ax2 = plt.subplots()
ax2.plot(df["Usia"], df["Dana Disetor"], label="Dana Disetor")
ax2.plot(df["Usia"], df["Aset"], label="Total Aset")
ax2.legend()
ax2.set_title("Dana Disetor vs Nilai Investasi")
g2.pyplot(fig2)

# =====================================================
# SCENARIO TABLE
# =====================================================
st.subheader("📋 Scenario Analysis")

scenario = []
for label, r in {
    "Pesimis": expected_return - 0.03,
    "Base": expected_return,
    "Optimis": expected_return + 0.03
}.items():
    bal = 0
    for _ in range(months):
        bal = bal * (1 + r/12) + monthly_invest
    scenario.append([label, f"{r*100:.1f}%", f"Rp {bal:,.0f}"])

st.dataframe(
    pd.DataFrame(scenario, columns=["Skenario", "Return", "Aset Akhir"]),
    use_container_width=True
)

# =====================================================
# MONTE CARLO SIMULATION
# =====================================================
st.subheader("🎲 Monte Carlo Simulation")

sim = 3000
results = []

for _ in range(sim):
    bal = 0
    for _ in range(months):
        rnd = np.random.normal(expected_return, 0.04) / 12
        bal = bal * (1 + rnd) + monthly_invest
    results.append(bal)

results = np.array(results)
prob = (results >= target_aset).mean()

fig_mc, ax_mc = plt.subplots()
ax_mc.hist(results, bins=40)
ax_mc.axvline(target_aset)
ax_mc.set_title("Distribusi Aset Akhir")
st.pyplot(fig_mc)

st.metric("Probability of Success", f"{prob*100:.1f}%")

# =====================================================
# PASSIVE INCOME & ALLOCATION
# =====================================================
st.subheader("💸 Pendapatan Pasif Pasca Financial Freedom")

yield_obl = st.slider(
    "Yield obligasi (%)",
    min_value=3.0,
    max_value=12.0,
    value=6.0,
    key="yield_obligasi"
) / 100

monthly_income = target_aset * yield_obl / 12

p1, p2 = st.columns(2)
card(p1, "Pendapatan Bulanan", f"Rp {monthly_income:,.0f}")
card(p2, "Target Aset", f"Rp {target_aset:,.0f}")

# =====================================================
# EXPORT PDF
# =====================================================
st.subheader("📄 Export Financial Report")

if st.button("Download PDF Report", key="download_pdf"):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer)
    styles = getSampleStyleSheet()

    content = [
        Paragraph("Financial Freedom Report", styles["Title"]),
        Paragraph(f"Profil Investor: {profil}", styles["Normal"]),
        Paragraph(f"Target Usia: {usia_target}", styles["Normal"]),
        Paragraph(f"Target Aset: Rp {target_aset:,.0f}", styles["Normal"]),
        Paragraph(f"Investasi Bulanan: Rp {monthly_invest:,.0f}", styles["Normal"]),
        Paragraph(f"Probability of Success: {prob*100:.1f}%", styles["Normal"]),
    ]

    doc.build(content)

    st.download_button(
        "Klik untuk mengunduh",
        buffer.getvalue(),
        file_name="financial_report.pdf",
        mime="application/pdf",
        key="pdf_download_button"
    )

# =====================================================
# DISCLAIMER
# =====================================================
st.caption(
    "Disclaimer: Aplikasi ini bersifat edukatif dan bukan merupakan nasihat investasi."
)
